spring:
  datasource:
    url: jdbc:postgresql://localhost:4444/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always